
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 14 12:14:22 CET 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POSICION = 15;
  public static final int POSACCIONES = 9;
  public static final int COMA = 4;
  public static final int FONDO = 11;
  public static final int PERSONAJE = 12;
  public static final int INICIO = 10;
  public static final int ACCION = 13;
  public static final int EOF = 0;
  public static final int ESCENARIO = 2;
  public static final int OBJETO = 14;
  public static final int PARIZQ = 5;
  public static final int PLAN = 8;
  public static final int error = 1;
  public static final int FINSEC = 7;
  public static final int INISEC = 3;
  public static final int PARDER = 6;
  public static final int UBICACION = 16;
}

